### ISSUE TITLE
Publish latest changes to npm

### ISSUE THREAD

**Issue by ghost** [stoffern/gl-react-imagefilters#13]
Please 😄

**Comment by st0ffern** [comment]
Wierd, 0.1.7 should be latest and up to date with GitHub

**Comment by ghost** [comment]
@stoffern I thought https://github.com/stoffern/gl-react-imagefilters/commit/815862a21aa58aa8e1575a9c6fe1e15bf92e40f9 didn't make it to npm, I got an error related to PropType. I'll double check when I get back to work tomorrow and come back here.

**Comment by ghost** [comment]
@stoffern I checked real quick, seems to be because of https://github.com/gre/gl-react-negative/blob/master/src/Negative.js#L37

**Comment by ghost** [comment]
I will come up with a PR tomorrow on the other repo.
