### ISSUE TITLE
Can't find variable: Component

### ISSUE THREAD

**Issue by jniac** [stoffern/gl-react-imagefilters#18]
Working with `React-Native`,  
i've just installed the whole stuff:  

from my package.json:
```json
    "gl-react": "^2.3.1",
    "gl-react-imagefilters": "^0.1.9",
    "gl-react-native": "^2.48.0",
```

but when i add `import ImageFilter from 'gl-react-imagefilters'`
i got that warning: 
```
Can't find variable: Component
<unknown>
Negative.js:33
```

@ that line i got from `Negative.js` the following code : 
```javascript
var Negative = function (_Component) {
  _inherits(Negative, _Component);

  function Negative() {
    _classCallCheck(this, Negative);

    return _possibleConstructorReturn(this, (Negative.__proto__ || Object.getPrototypeOf(Negative)).apply(this, arguments));
  }

  _createClass(Negative, [{
    key: "render",
    value: function render() {
      var _props = this.props,
          t = _props.children,
          factor = _props.factor;

      return _react2.default.createElement(_glReact.Node, {
        shader: shaders.Negative,
        uniforms: {
          t: t,
          factor: factor
        }
      });
    }
  }]);

  return Negative;
}(Component);
```

How to let Negative.js access to Component (React.Component?) ?
Did i miss something ?

**Comment by st0ffern** [comment]
That is not a good practice or a webpacked code. i will not dive into that.

**Comment by jniac** [comment]
Not my own code!
Negative.js is part of the gl-react-imagefilters package!
The code above is from `gl-react-negative/lib`

**Comment by jniac** [comment]
Ok, and the source code (from `gl-react-negative/lib`) is :
 
```javascript
import React from "react";
import { Node, Shaders } from "gl-react";
import PropTypes from "prop-types";

const shaders = Shaders.create({
  Negative: {
    frag: `precision highp float;
varying vec2 uv;
uniform sampler2D t;
uniform float factor;

void main () {
  vec4 c = texture2D(t, uv);
  gl_FragColor = vec4(mix(c.rgb, 1.0 - c.rgb, factor), c.a);
}`
  }
});

export default class Negative extends Component {
  static propTypes = {
    children: PropTypes.any.isRequired,
    factor: PropTypes.number
  };
  static defaultProps = {
    factor: 1
  };
  render() {
    const { children: t, factor } = this.props;
    return (
      <Node
        shader={shaders.Negative}
        uniforms={{
          t,
          factor
        }}
      />
    );
  }
}
```

which is invalid since `Component` (@line 19) is never declared.
```javascript
export default class Negative extends Component {
```

2 solutions:
- change line19 by
```javascript
export default class Negative extends React.Component {
```
- change line 1 by
```javascript
import React, { Component } from "react";
```
then rebuild `lib/`

The problem is not coming from `gl-react-imagefilters` but from `gl-react-negative`.
From git history i think i understand the typo is coming from gl-react V3 migration.

However i do not understand how that code can work, did you use `Component` (from React) as a global variable ?

**Comment by st0ffern** [comment]
This is a problem with gl-react-negative.. i have commented it here:
https://github.com/gre/gl-react-negative/commit/6ab299a4aeff9234dd15bb05c05360dfde35f434#r27692233

**Comment by st0ffern** [comment]
fix added here: a689c9e5f73a4dee68c3bc36bbeba339a11c53d9

**Comment by jniac** [comment]
thx, Christopher
i noticed that several package are concerned by that typo. Currently [gl-react-hue-rotate](https://github.com/gre/gl-react-hue-rotate/blob/master/src/HueRotate.js) is missing the same import. Does it means that you'll have to fix it too ?

Besides, i'm still new to NPM, package.json etc., since the published npm module is the same (referencing `"gl-react-negative": "^2.0.0"`), how can i use the fix you made?

**Comment by st0ffern** [comment]
please use stackoverflow for those questions.
I have pushed a update that will automatic downgrade your gl-react-negative repo when installing latest version of this repo. Please report problems with other repos at the spesific repos so that the owners or contributers can update the bugs.
