### ISSUE TITLE
Documentation mentions Sepia twice with different defaults

### ISSUE THREAD

**Issue by rgovindji** [stoffern/gl-react-imagefilters#2]
Just noticed this:
- sepia: optionally the intensity of the effect. 1.0 is normal. higher than 1 will add sepia.
- sepia: optional input to adjust the sepia filter (Default: 0 )

**Comment by st0ffern** [comment]
@rgovindji well spotted.
It was my documentation on `gl-react-sepia` that was wrong.
README.md changed.
