### ISSUE TITLE
Undefined is not an object (evaluating '_glReact2.default.createComponent')

### ISSUE THREAD

**Issue by josephmaxim** [stoffern/gl-react-imagefilters#4]
**_Bug Report_**

After installing with yarn, also tried with npm. (packager restarted)

`"dependencies": {
    "gl-react": "^3.6.0",
    "gl-react-imagefilters": "^0.1.5",
    "gl-react-native": "^3.6.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-navigation": "^1.0.0-beta.10",
  },`

![simulator screen shot jun 22 2017 5 38 27 pm](https://user-images.githubusercontent.com/10732770/27457258-fb673fd8-5771-11e7-82b6-250f97eab952.png)

**Comment by st0ffern** [comment]
Wrong gl-react and gr-react-native se theyr repos

**Comment by leoabacade** [comment]
facing the same issue, what do you mean wrong gl-react and gl-react-native?
i install it by npm, shouldn't be wrong since i didn't change it at all.

    "gl-react": "^3.15.0",
    "gl-react-dom": "^3.15.0",
    "gl-react-imagefilters": "^0.1.10",
    "gl-react-native": "^3.15.0",

**Comment by st0ffern** [comment]
gl-react-imagefilters needs gl-react v2

**Comment by leoabacade** [comment]
＠stoffern any idea how to install gl-react v2? their npm i --save gl-react@2.3.1 will only save old version?
