### ISSUE TITLE
How to export the image with filters?

### ISSUE THREAD

**Issue by mannol** [stoffern/gl-react-imagefilters#5]
You can apply filters to an image but, how to store the filtered image on disk?

**Comment by st0ffern** [comment]
see `gl-react-native` captureframe

**Comment by mannol** [comment]
Neat. Thanks!

**Comment by oyeanuj** [comment]
@stoffern For React-Web, I couldn't seem to find any API here - https://gl-react-cookbook.surge.sh/api.

Do you by any chance know which API might be the most relevant? 

Thanks!
